#!/bin/bash
# SessionStart hook — makes a fresh Claude Code on the web container able to run
# `npm run lint` / `npm run typecheck`, and gives the session the treg CLI.
#
# A web container is cloned fresh and has no node_modules, so without this every
# session starts unable to run the repo's own checks.
set -euo pipefail

# Local machines already have their own setup; don't touch them.
[ "${CLAUDE_CODE_REMOTE:-}" = "true" ] || exit 0

cd "${CLAUDE_PROJECT_DIR:?CLAUDE_PROJECT_DIR is not set}"

# --- the site itself -------------------------------------------------------
# `install`, not `ci`: the container image is cached after this hook completes,
# and install reuses that cache across sessions where ci would delete it first.
echo "→ npm install"
npm install --no-audit --no-fund

# `npm run typecheck` fails on a fresh clone without this. next-env.d.ts is
# gitignored and generated by a Next build, and it is what declares the image
# modules that About/Work/AfterPane import — so tsc reports five phantom
# "cannot find module" errors until it exists. typegen writes it in about a
# second, where a full build would take far longer to prove the same point.
echo "→ next typegen"
npx --no-install next typegen

# --- treg CLI (optional) ---------------------------------------------------
# uv and treg both land in ~/.local/bin, which is not on PATH by default here.
export PATH="$HOME/.local/bin:$PATH"
if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$CLAUDE_ENV_FILE"
fi

if [ -z "${TREG_TOKEN:-}" ]; then
  echo "→ TREG_TOKEN not set — skipping the treg CLI."
  echo "  Set it on the Claude Code environment to enable it (see README)."
  exit 0
fi

# Installed WITHOUT --token on purpose. Passing the token makes the installer
# also run `treg mcp install`, which registers the MCP server at user scope —
# a second copy of the one .mcp.json already provides per-repo. Sign in
# separately and the MCP server stays defined in exactly one place.
if command -v treg >/dev/null 2>&1; then
  echo "→ treg CLI already present"
else
  echo "→ installing the treg CLI"
  if ! curl -fsSL https://treg.to/install.sh | sh >/dev/null 2>&1; then
    echo "‼ treg install failed — continuing without it (the MCP server is unaffected)."
    exit 0
  fi
fi

if treg login --token "$TREG_TOKEN" >/dev/null 2>&1; then
  echo "→ treg signed in ($(treg balance 2>/dev/null | grep -o '\$[0-9.]*' | head -1) balance)"
else
  echo "‼ treg login failed — the token may have expired. Calls will 401 until it is replaced."
fi
